site_name: BRASA
repo_name: adriytkr/brasa
repo_url: https://github.com/adriytkr/brasa
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt-br
  favicon: assets/favicon.ico
  logo: assets/brasa.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adriytkr/brasa
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/brasa/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCZT_F8MfKNgtW3Qut-6ylsg/
  alternate:
    - name: English
      link: /
      lang: en
    - name: Português
      link: /pt-br
      lang: pt-br
nav:
  - Home:
    - Welcome: index.md
    - Overview: overview.md
    - Related Languages: related-languages.md
    - Architecture and Design Decisions: architecture-and-design-decisions.md
  - Tutorial:
      - tutorial/index.md
      - Getting Started:
        - Installation: tutorial/getting-started/installation.md
        - First Program: tutorial/getting-started/first-program.md
      - Fundamentals:
        - Variables: tutorial/fundamentals/variables.md
        - Operators: tutorial/fundamentals/operators.md
        - Input/Output: tutorial/fundamentals/input-output.md
        - Comments: tutorial/fundamentals/comments.md
        - Examples:
          - Average: tutorial/fundamentals/examples/average.md
      - Control Flow:
        - Conditions: tutorial/control-flow/conditions.md
        - Loops: tutorial/control-flow/loops.md
        - Scopes: tutorial/control-flow/scopes.md
        - Examples:
          - ExampleA: tutorial/control-flow/examples/exampleA.md
          - ExampleB: tutorial/control-flow/examples/exampleB.md
      - Arrays:
        - Introduction: tutorial/arrays/introduction.md
        - Examples:
          - ExampleA: tutorial/arrays/examples/exampleA.md
          - ExampleB: tutorial/arrays/examples/exampleB.md
      - Functions:
        - Introduction: tutorial/functions/introduction.md
      - Objects:
        - Introduction: tutorial/objects/introduction.md
      - Modules:
        - Introduction: tutorial/modules/introduction.md
        - Built-in Modules:
          - Standard: tutorial/modules/built-in-modules/std.md
          - Math: tutorial/modules/built-in-modules/math.md
  - Playground: playground.md
plugins:
  - search
