start: top_item+

?top_item: statement

?statement: declaration ";"
  | update_var ";"
  | diga_statement ";"
  | if_statement
  | while_statement
  | return_statement
  | function_def
  | function_call ";"
  | comparison ";"

declaration: PRIMITIVE_TYPE ID ":=" expr
update_var: ID ":=" expr
diga_statement: "diga" "(" expr ")"

PRIMITIVE_TYPE: "int"
  | "decimal"
  | "texto"
  | "logico"

?expr: comparison

?comparison: sum (COMP_OP sum)*
?sum: product (ADD_OP product)*
?product: atom (MUL_OP atom)*

?atom: DECIMAL -> decimal
  | INTEGER -> integer
  | STRING -> string
  | ID -> var_lookup
  | "verdadeiro" -> true_val
  | "falso" -> false_val
  | "(" expr ")"
  | function_call

ID: /[a-zA-Z_][a-zA-Z0-9_]*/
DECIMAL: /[0-9]+\.[0-9]+/
INTEGER: /[0-9]+/
STRING: /"[^"]*"/
ADD_OP: "+" | "-"
MUL_OP: "*" | "/"
COMP_OP: "==" | "!=" | ">" | "<" | ">=" | "<="

block: "{" statement* "}"

if_statement: "se" "(" expr ")" block ("senao" block)?

while_statement: "enquanto" "(" expr ")" block

%import common.WS
%ignore WS

COMMENT: /\/\/.*/
%ignore COMMENT

?return_type: PRIMITIVE_TYPE|"void"

function_def: "func" ID "(" (param ("," param)*)? ")" "->" return_type block
param: PRIMITIVE_TYPE ID
return_statement: "retorna" expr? ";"
function_call: ID "(" (expr ("," expr)*)? ")"

//?top_item:statement|func
//?expr:NUMBER|ID|call
//OPERATOR: "+" | "-" | "*" | "/"
//NUMBER: /[0-9]+/
//calculation: expr OPERATOR expr
//ID: /[a-zA-Z_][a-zA-Z0-9_]*/
//call: ID "(" (expr ("," expr)*)? ")"
//statement: (calculation|call) ";"
//func: "func" ID "(" arg_list? ")" "{" statement* "}"
//arg_list: ID ("," ID)*
//block: "{" (statement | func | block)* "}"
